{
  "Header": {
    "Original": "CVE-2020-15890 (LuaJit through 2.1.0-beta3 has an out-of-bounds read because __gc hand ...)",
    "Line": 276719,
    "ID": "CVE-2020-15890",
    "Description": "(LuaJit through 2.1.0-beta3 has an out-of-bounds read because __gc hand ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2296-1}",
      "Line": 276720,
      "Type": "xref",
      "Bugs": [
        "DLA-2296-1"
      ]
    },
    {
      "Original": "- luajit 2.1.0~beta3+git20210112+dfsg-2 (unimportant; bug #966148)",
      "Line": 276721,
      "Type": "package",
      "Package": "luajit",
      "Kind": "fixed",
      "Version": "2.1.0~beta3+git20210112+dfsg-2",
      "Severity": "unimportant",
      "BugNo": 966148
    },
    {
      "Original": "NOTE: https://github.com/LuaJIT/LuaJIT/issues/601",
      "Line": 276722,
      "Type": "NOTE",
      "Description": "https://github.com/LuaJIT/LuaJIT/issues/601"
    },
    {
      "Original": "NOTE: https://github.com/LuaJIT/LuaJIT/commit/53f82e6e2e858a0a62fd1a2ff47e9866693382e6",
      "Line": 276723,
      "Type": "NOTE",
      "Description": "https://github.com/LuaJIT/LuaJIT/commit/53f82e6e2e858a0a62fd1a2ff47e9866693382e6"
    },
    {
      "Original": "NOTE: No security impact, only \"exploitable\" with untrusted Lua code",
      "Line": 276724,
      "Type": "NOTE",
      "Description": "No security impact, only \"exploitable\" with untrusted Lua code"
    }
  ]
}