{
  "Header": {
    "Original": "CVE-2019-10904 (Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and r ...)",
    "Line": 361927,
    "ID": "CVE-2019-10904",
    "Description": "(Roundup 1.6 allows XSS via the URI because frontends/roundup.cgi and r ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1750-1}",
      "Line": 361928,
      "Type": "xref",
      "Bugs": [
        "DLA-1750-1"
      ]
    },
    {
      "Original": "- roundup \u003cremoved\u003e (bug #926587)",
      "Line": 361929,
      "Type": "package",
      "Package": "roundup",
      "Kind": "removed",
      "BugNo": 926587
    },
    {
      "Original": "NOTE: https://github.com/python/bugs.python.org/issues/34",
      "Line": 361930,
      "Type": "NOTE",
      "Description": "https://github.com/python/bugs.python.org/issues/34"
    },
    {
      "Original": "NOTE: https://issues.roundup-tracker.org/issue2551035",
      "Line": 361931,
      "Type": "NOTE",
      "Description": "https://issues.roundup-tracker.org/issue2551035"
    },
    {
      "Original": "NOTE: https://bitbucket.org/python/roundup/commits/51682dc2cd7e28421d749117c25bec58f632ee5f",
      "Line": 361932,
      "Type": "NOTE",
      "Description": "https://bitbucket.org/python/roundup/commits/51682dc2cd7e28421d749117c25bec58f632ee5f"
    }
  ]
}