{
  "Header": {
    "Original": "CVE-2020-15801 (In Python 3.8.4, sys.path restrictions specified in a python38._pth fi ...)",
    "Line": 278671,
    "ID": "CVE-2020-15801",
    "Description": "(In Python 3.8.4, sys.path restrictions specified in a python38._pth fi ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.9 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 278672,
      "Type": "package",
      "Package": "python3.9",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.8 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 278673,
      "Type": "package",
      "Package": "python3.8",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.7 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 278674,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.5 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 278675,
      "Type": "package",
      "Package": "python3.5",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (Windows-specific)",
      "Line": 278676,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    }
  ]
}