{
  "Header": {
    "Original": "CVE-2022-0725 (A flaw was found in keepass. The vulnerability occurs due to logging t ...)",
    "Line": 171269,
    "ID": "CVE-2022-0725",
    "Description": "(A flaw was found in keepass. The vulnerability occurs due to logging t ...)"
  },
  "Annotations": [
    {
      "Original": "NOTE: Non-issue, broken report against keepass2, couldn't be reproduced with",
      "Line": 171270,
      "Type": "NOTE",
      "Description": "Non-issue, broken report against keepass2, couldn't be reproduced with"
    },
    {
      "Original": "NOTE: Debian, Fedora and by upstream, see bug #1008022",
      "Line": 171271,
      "Type": "NOTE",
      "Description": "Debian, Fedora and by upstream, see bug #1008022"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2052696",
      "Line": 171272,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2052696"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/keepass/discussion/329220/thread/da7546b7e1/",
      "Line": 171273,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/keepass/discussion/329220/thread/da7546b7e1/"
    },
    {
      "Original": "NOTE: https://sourceforge.net/p/keepass/discussion/329220/thread/33d6afdc/",
      "Line": 171274,
      "Type": "NOTE",
      "Description": "https://sourceforge.net/p/keepass/discussion/329220/thread/33d6afdc/"
    }
  ]
}