{
  "Header": {
    "Original": "CVE-2019-12312 (In Libreswan 3.27 an assertion failure can lead to a pluto IKE daemon  ...)",
    "Line": 350728,
    "ID": "CVE-2019-12312",
    "Description": "(In Libreswan 3.27 an assertion failure can lead to a pluto IKE daemon  ...)"
  },
  "Annotations": [
    {
      "Original": "[experimental] - libreswan 3.28-1",
      "Line": 350729,
      "Type": "package",
      "Release": "experimental",
      "Package": "libreswan",
      "Kind": "fixed",
      "Version": "3.28-1"
    },
    {
      "Original": "- libreswan 3.27-5 (bug #929916)",
      "Line": 350730,
      "Type": "package",
      "Package": "libreswan",
      "Kind": "fixed",
      "Version": "3.27-5",
      "BugNo": 929916
    },
    {
      "Original": "NOTE: https://github.com/libreswan/libreswan/issues/246",
      "Line": 350731,
      "Type": "NOTE",
      "Description": "https://github.com/libreswan/libreswan/issues/246"
    },
    {
      "Original": "NOTE: https://github.com/libreswan/libreswan/commit/7142d2c37d58cf024595a7549f0fb0d3946682f8",
      "Line": 350732,
      "Type": "NOTE",
      "Description": "https://github.com/libreswan/libreswan/commit/7142d2c37d58cf024595a7549f0fb0d3946682f8"
    },
    {
      "Original": "NOTE: https://libreswan.org/security/CVE-2019-12312/CVE-2019-12312.txt",
      "Line": 350733,
      "Type": "NOTE",
      "Description": "https://libreswan.org/security/CVE-2019-12312/CVE-2019-12312.txt"
    },
    {
      "Original": "NOTE: https://libreswan.org/security/CVE-2019-12312/libreswan-3.27-CVE-2019-12312.patch",
      "Line": 350734,
      "Type": "NOTE",
      "Description": "https://libreswan.org/security/CVE-2019-12312/libreswan-3.27-CVE-2019-12312.patch"
    }
  ]
}