{
  "Header": {
    "Original": "CVE-2020-13254 (An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0 ...)",
    "Line": 281869,
    "ID": "CVE-2020-13254",
    "Description": "(An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0 ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4705-1 DLA-2233-1}",
      "Line": 281870,
      "Type": "xref",
      "Bugs": [
        "DSA-4705-1",
        "DLA-2233-1"
      ]
    },
    {
      "Original": "- python-django 2:2.2.13-1 (bug #962323)",
      "Line": 281871,
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "2:2.2.13-1",
      "BugNo": 962323
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2020/06/03/1",
      "Line": 281872,
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2020/06/03/1"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/2c82414914ae6476be5a166be9ff49c24d0d9069 (master)",
      "Line": 281873,
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/2c82414914ae6476be5a166be9ff49c24d0d9069 (master)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/580bd64c0482ae9b7c05715390e25f4405a12719 (3.1 branch)",
      "Line": 281874,
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/580bd64c0482ae9b7c05715390e25f4405a12719 (3.1 branch)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693 (3.0 branch)",
      "Line": 281875,
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/84b2da5552e100ae3294f564f6c862fef8d0e693 (3.0 branch)"
    },
    {
      "Original": "NOTE: https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206 (2.2 branch)",
      "Line": 281876,
      "Type": "NOTE",
      "Description": "https://github.com/django/django/commit/07e59caa02831c4569bbebb9eb773bdd9cb4b206 (2.2 branch)"
    },
    {
      "Original": "NOTE: Regression https://code.djangoproject.com/ticket/31654",
      "Line": 281877,
      "Type": "NOTE",
      "Description": "Regression https://code.djangoproject.com/ticket/31654"
    }
  ]
}