{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "kernel",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "kernel-rt",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2024-02-26T00:00:00Z",
  "bugzilla": {
    "description": "kernel: use after free in i2c",
    "id": "2266296",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2266296"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-416",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2019-25162",
  "document_distribution": "",
  "details": [
    "An out-of-bounds (OOB) memory access flaw was found in the i2c driver module in the Linux kernel."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2019-25162\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-25162\nhttps://git.kernel.org/stable/c/12b0606000d0828630c033bf0c74c748464fe87d\nhttps://git.kernel.org/stable/c/23a191b132cd87f746c62f3dc27da33683d85829\nhttps://git.kernel.org/stable/c/35927d7509ab9bf41896b7e44f639504eae08af7\nhttps://git.kernel.org/stable/c/81cb31756888bb062e92d2dca21cd629d77a46a9\nhttps://git.kernel.org/stable/c/871a1e94929a27bf6e2cd99523865c840bbc2d87\nhttps://git.kernel.org/stable/c/e4c72c06c367758a14f227c847f9d623f1994ecf\nhttps://git.kernel.org/stable/c/e6412ba3b6508bdf9c074d310bf4144afa6aec1a\nhttps://git.kernel.org/stable/c/e8e1a046cf87c8b1363e5de835114f2779e2aaf4"
  ]
}