{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2020-09-29T00:00:00Z",
      "advisory": "RHSA-2020:4030",
      "package": "exiv2-0:0.27.0-3.el7_8",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2021-05-18T00:00:00Z",
      "advisory": "RHSA-2021:1758",
      "package": "exiv2-0:0.27.3-2.el8",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "exiv2",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "compat-exiv2-023",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "compat-exiv2-026",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Will not fix",
      "package_name": "compat-exiv2-026",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2019-10-06T00:00:00Z",
  "bugzilla": {
    "description": "exiv2: out-of-bounds read in CiffDirectory::readDirectory due to lack of size check",
    "id": "1773683",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1773683"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.5",
    "cvss3_scoring_vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2019-17402",
  "document_distribution": "",
  "details": [
    "Exiv2 0.27.2 allows attackers to trigger a crash in Exiv2::getULong in types.cpp when called from Exiv2::Internal::CiffDirectory::readDirectory in crwimage_int.cpp, because there is no validation of the relationship of the total size to the offset and size.",
    "An out of bounds read vulnerability was discovered in the way exiv2 parses Canon raw format (CRW) images. An application that uses exiv2 library to parse untrusted images may be vulnerable to this flaw, which could be used by an attacker to extract data from the application's memory or make it crash. The biggest threat with this vulnerability is availability of the system."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2019-17402\nhttps://nvd.nist.gov/vuln/detail/CVE-2019-17402"
  ]
}