{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "automation-controller",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "python-jose",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-04-26T00:00:00Z",
  "bugzilla": {
    "description": "python-jose: allows attackers to cause a denial of service",
    "id": "2277300",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2277300"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2024-33664",
  "document_distribution": "",
  "details": [
    "python-jose through 3.3.0 allows attackers to cause a denial of service (resource consumption) during a decode via a crafted JSON Web Encryption (JWE) token with a high compression ratio, aka a \"JWT bomb.\" This is similar to CVE-2024-21319."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-33664\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-33664"
  ]
}